### PR TITLE
Support run with pr number

### PR DESCRIPTION
**Pull request by fisker**
Support `run with pr 1234`

### CODE REVIEW

**Comment by fisker** [comment]
Not sure if we can install `Github CLI`, need merge and test.

**Comment by fisker** [comment]
Working https://github.com/fisker/prettier-regression-testing/issues/2#issuecomment-734130893

**Review by sosukesuzuki — APPROVED** [review]
Thank you. I regret making this code sloppy... I'll rewrite this with TypeScript.

**Comment by fisker** [comment]
I  forgot add this command to  readme, can you add it ?

**Pull request merged**
